version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
      POSTGRES_DB: energy
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
